/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

import controller.donercontroller;
import models.donermodel;

/**
 *
 * @author user
 */
public class adddonorlist extends javax.swing.JFrame {

    /**
     * Creates new form adddonorlist
     */
    public adddonorlist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        snText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dNameText = new javax.swing.JTextField();
        dNumberText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        organText = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 520));
        getContentPane().setLayout(null);

        snText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snTextActionPerformed(evt);
            }
        });
        getContentPane().add(snText);
        snText.setBounds(340, 200, 260, 30);

        jLabel5.setText("SN:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 200, 140, 30);

        jLabel2.setText("Doner Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 240, 140, 30);

        dNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dNameTextActionPerformed(evt);
            }
        });
        getContentPane().add(dNameText);
        dNameText.setBounds(340, 240, 260, 30);

        dNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dNumberTextActionPerformed(evt);
            }
        });
        getContentPane().add(dNumberText);
        dNumberText.setBounds(340, 280, 260, 30);

        jLabel3.setText("Doner phone no. :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 280, 140, 30);

        jLabel4.setText("Doantion Organ  :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 320, 100, 30);

        organText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organTextActionPerformed(evt);
            }
        });
        getContentPane().add(organText);
        organText.setBounds(340, 320, 260, 30);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn);
        saveBtn.setBounds(340, 360, 260, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jButton3.setText("ABOUT US");

        jButton4.setText("APPOINTMENT");

        jButton5.setText("LOGIN");

        jButton2.setText("UPDATES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(12, 12, 12)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(480, 10, 452, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BG frame.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 930, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void snTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snTextActionPerformed

    private void dNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dNameTextActionPerformed

    private void dNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dNumberTextActionPerformed

    private void organTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organTextActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
      String sn = snText.getText();
        String dn = dNameText.getText();
        String dn1 = dNumberText.getText();
        String organ = organText.getText();
        // int a = 0;

        if(sn.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter the serial number");
        }else if(dn.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter the donor name");
        }else if(dn1.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter the donor number");
        }else if(organ.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter the organ");
        }else{
            try {
                int sn1 = Integer.parseInt(sn);
                Double dn2 = Double.parseDouble(dn1);
                donermodel doner = new donermodel(sn1, dn, dn2, organ);
                donercontroller donercontroller = new donercontroller();
                int res = donercontroller.insertdetails(doner);
            } catch (Exception e) {
                // TODO: handle exception
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adddonorlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adddonorlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adddonorlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adddonorlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adddonorlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dNameText;
    private javax.swing.JTextField dNumberText;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField organText;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField snText;
    // End of variables declaration//GEN-END:variables
}
