/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import models.drlistmodel;
import controller.drlistcontroller;
import database.DbConnection;
import java.sql.ResultSet;

/**
 *
 * @author user
 */
public class doctorlistupdate extends javax.swing.JFrame {

    /**
     * Creates new form doctorlistupdate
     */
    public doctorlistupdate() {
        initComponents();
        view();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DTable = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Depart = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        doctor_id = new javax.swing.JTextField();
        special = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        delBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 650));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));

        jButton1.setText("LOGIN");

        jButton2.setText("ABOUT US");

        jButton3.setText("UPDATES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("HOME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(27, 27, 27)
                .addComponent(jButton3)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(660, 30, 420, 90);

        DTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor_id", "Doctor name", "Age", "Department", "Speciality"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DTable.setGridColor(java.awt.Color.white);
        DTable.setShowHorizontalLines(true);
        DTable.setShowVerticalLines(true);
        DTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(530, 200, 510, 270);

        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBtn.setText("Update Doctor");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn);
        updateBtn.setBounds(760, 530, 160, 27);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Health Track logo smaller.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 10, 210, 180);

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));
        jPanel1.setLayout(null);

        Depart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Depart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Depart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DepartFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DepartFocusLost(evt);
            }
        });
        Depart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartActionPerformed(evt);
            }
        });
        jPanel1.add(Depart);
        Depart.setBounds(140, 170, 190, 30);

        age.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFocusLost(evt);
            }
        });
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel1.add(age);
        age.setBounds(140, 130, 190, 30);

        lname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnameFocusLost(evt);
            }
        });
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel1.add(lname);
        lname.setBounds(140, 90, 190, 30);

        doctor_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doctor_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        doctor_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                doctor_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                doctor_idFocusLost(evt);
            }
        });
        doctor_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctor_idActionPerformed(evt);
            }
        });
        jPanel1.add(doctor_id);
        doctor_id.setBounds(140, 10, 190, 30);

        special.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        special.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        special.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                specialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                specialFocusLost(evt);
            }
        });
        special.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialActionPerformed(evt);
            }
        });
        jPanel1.add(special);
        special.setBounds(140, 210, 190, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Doctor ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 20, 98, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Dr. Age");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 140, 98, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Specalist");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 220, 98, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Department");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 180, 110, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Dr. Last Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 100, 110, 20);

        fname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameFocusLost(evt);
            }
        });
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel1.add(fname);
        fname.setBounds(140, 50, 190, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Dr. First Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 60, 98, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 280, 340, 260);

        addBtn.setBackground(new java.awt.Color(204, 204, 204));
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBtn.setText("Add doctor");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn);
        addBtn.setBounds(60, 560, 107, 27);

        jPanel3.setBackground(new java.awt.Color(153, 102, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Doctors List");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(200, 220, 120, 50);

        delBtn.setBackground(new java.awt.Color(204, 204, 204));
        delBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delBtn.setText("Delete doctor");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        getContentPane().add(delBtn);
        delBtn.setBounds(350, 560, 130, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BG frame.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 1080, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void doctor_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_doctor_idFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_doctor_idFocusGained

    private void doctor_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_doctor_idFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_doctor_idFocusLost

    private void doctor_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctor_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctor_idActionPerformed

    private void lnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameFocusGained

    private void lnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameFocusLost

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void ageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFocusGained

    private void ageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFocusLost

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void specialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_specialFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_specialFocusGained

    private void specialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_specialFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_specialFocusLost

    private void DepartFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DepartFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartFocusGained

    private void DepartFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DepartFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartFocusLost

    private void specialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
    String id=doctor_id.getText();
    String Fname=fname.getText();
    String Lname=lname.getText();
    String Age = age.getText();
    String Depatment=Depart.getText();
    String Special=special.getText();
    System.out.println(id+" "+Fname+" "+Lname+" "+Age+" "+Depatment+" "+Special);
    int a = 0;
    
    if (Fname.equals("")){
        JOptionPane.showMessageDialog(null, "FNAME IS MISSING.");
            a = 1;
    }
    if (Lname.equals("")){
        JOptionPane.showMessageDialog(null, "LNAME IS MISSING.");
            a = 1;
    }
    if (Age.equals("")){
        JOptionPane.showMessageDialog(null, "Age IS MISSING.");
            a = 1;
    }
    if (Depatment.equals("")){
        JOptionPane.showMessageDialog(null, "Depatment IS MISSING.");
            a = 1;
    }
    if (Special.equals("")){
        JOptionPane.showMessageDialog(null, "Specialization IS MISSING.");
            a = 1;
    }
    if (a==0){
        try{
            System.out.println(id+" "+Fname+" "+Lname+" "+Age+" "+Depatment+" "+Special);
            // int Id=Integer.parseInt(id);
            int age=Integer.parseInt(Age);
            drlistmodel d1= new drlistmodel(0,Fname,Lname,age, Depatment,Special);
//            drlistcontroller 
            drlistcontroller sc = new drlistcontroller();
            int insertdoctor = sc.insertdetails(d1);

                if (insertdoctor > 0) {
                    System.out.println("data inserted");
                } else {
                    System.out.println("Failed to insert data");
                }
                JOptionPane.showMessageDialog(null, "VALIDATION SUCCESSFUL");
                view();
                
            } 
        catch (Exception e) {
                // TODO: handle exception
                JOptionPane.showMessageDialog(null, e);
                System.out.printf(null,e);
            }
            
        }
    
    // TODO add your handling code here:
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

       
        String id=doctor_id.getText();
    String Fname=fname.getText();
    String Lname=lname.getText();
    String Age = age.getText();
    String Depatment=Depart.getText();
    String Special=special.getText();
    System.out.println(id+" "+Fname+" "+Lname+" "+Age+" "+Depatment+" "+Special);
    int a = 0;
    
    if (Fname.equals("")){
        JOptionPane.showMessageDialog(null, "FNAME IS MISSING.");
            a = 1;
    }
    if (Lname.equals("")){
        JOptionPane.showMessageDialog(null, "LNAME IS MISSING.");
            a = 1;
    }
    if (Age.equals("")){
        JOptionPane.showMessageDialog(null, "Age IS MISSING.");
            a = 1;
    }
    if (Depatment.equals("")){
        JOptionPane.showMessageDialog(null, "Depatment IS MISSING.");
            a = 1;
    }
    if (Special.equals("")){
        JOptionPane.showMessageDialog(null, "Specialization IS MISSING.");
            a = 1;
    }
    if (a==0){
        try{
            System.out.println(id+" "+Fname+" "+Lname+" "+Age+" "+Depatment+" "+Special);
            int Id=Integer.parseInt(id);
            int age=Integer.parseInt(Age);
            drlistmodel d1= new drlistmodel(Id,Fname,Lname,age, Depatment,Special);
//            drlistcontroller 
            drlistcontroller sc = new drlistcontroller();
            int insertdoctor = sc.updateDoctor(d1);

                if (insertdoctor > 0) {
                    System.out.println("data inserted");
                } else {
                    System.out.println("Failed to insert data");
                }
                JOptionPane.showMessageDialog(null, "Update SUCCESSFUL");
                view();
                
            } 
        catch (Exception e) {
                // TODO: handle exception
                JOptionPane.showMessageDialog(null, e);
                System.out.printf(null,e);
            }
            
        }
    
    // TODO add your handling code here:
        
    }
        // DTable.setModel(DbUtils.resultSetToTableModel(result));
     
         // TODO add your handling code here:
    //GEN-LAST:event_updateBtnActionPerformed

    private void fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameFocusGained

    private void fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameFocusLost

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void DepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
    String Fname=fname.getText();
    String Lname=lname.getText();
    String Age = age.getText();
    String Depatment=Depart.getText();
    String Special=special.getText();
    String id=doctor_id.getText();
    try{
            int Id=Integer.parseInt(id);
            int age=Integer.parseInt(Age);
            drlistmodel d1= new drlistmodel(Id,Fname,Lname, age, Depatment, Special);
//            drlistcontroller 
            drlistcontroller sc = new drlistcontroller();
            int deldoctor = sc.deleteDoctor(d1);

                if (deldoctor > 0) {
                    System.out.println("delete inserted");
                } else {
                    System.out.println("Failed to insert data");
                }
                JOptionPane.showMessageDialog(null, "Delete Successfull.");
                view();
                
            } 
        catch (Exception e) {
                // TODO: handle exception
                JOptionPane.showMessageDialog(null, e);
                System.out.printf(null,e);
            }

        
           
    }//GEN-LAST:event_delBtnActionPerformed

    private void DTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DTableMouseClicked
        int i = DTable.getSelectedRow();
        TableModel model = DTable.getModel();
        doctor_id.setText(model.getValueAt(i, 0).toString());
        String name = model.getValueAt(i, 1).toString();
        String[] parts = name.split(" ");
        String part1 = parts[0];
        String part2 = parts[1];
        fname.setText(part1);
        lname.setText(part2);
        age.setText(model.getValueAt(i, 2).toString());
        Depart.setText(model.getValueAt(i, 3).toString());
        special.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_DTableMouseClicked
public void view(){
    DefaultTableModel model = (DefaultTableModel) DTable.getModel();
    model.setRowCount(0);

    try {
        ResultSet result = new drlistcontroller().selectdetails();
        while (result.next()) {
        String id = result.getString(1);
        String fname = result.getString(2);
        String lname = result.getString(3);
        String age = result.getString(4);
        String depart = result.getString(5);
        String special = result.getString(6);
        model.addRow(new Object[]{id,(fname+" "+ lname),age,depart,special});
        }
    } catch (Exception e) {
        System.out.println(e);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctorlistupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctorlistupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctorlistupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctorlistupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctorlistupdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable DTable;
    private javax.swing.JTextField Depart;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField age;
    private javax.swing.JButton delBtn;
    private javax.swing.JTextField doctor_id;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField special;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    private void prepareStatement(String sql) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
