package view;

import controller.donercontroller;
import models.donermodel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rajil
 */
public class DONERLISTFORM extends javax.swing.JFrame {

    /**
     * Creates new form DONERLISTFORM
     */
    public DONERLISTFORM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Dname = new javax.swing.JTextField();
        Dnumber = new javax.swing.JTextField();
        organ = new javax.swing.JTextField();
        sn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jButton3.setText("ABOUT US");

        jButton4.setText("APPOINTMENT");

        jButton5.setText("LOGIN");

        jButton2.setText("UPDATES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(12, 12, 12)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(480, 10, 454, 60);

        Dname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DnameActionPerformed(evt);
            }
        });
        getContentPane().add(Dname);
        Dname.setBounds(340, 240, 260, 30);

        Dnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DnumberActionPerformed(evt);
            }
        });
        getContentPane().add(Dnumber);
        Dnumber.setBounds(340, 280, 260, 30);

        organ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organActionPerformed(evt);
            }
        });
        getContentPane().add(organ);
        organ.setBounds(340, 320, 260, 30);

        sn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snActionPerformed(evt);
            }
        });
        getContentPane().add(sn);
        sn.setBounds(340, 200, 260, 30);

        jLabel2.setText("Doner Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 240, 140, 30);

        jLabel3.setText("Doner phone no. :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 280, 140, 30);

        jLabel4.setText("Doantion Organ  :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 320, 100, 30);

        jLabel5.setText("SN:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 200, 140, 30);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 360, 260, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BG frame.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 930, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DnameActionPerformed

    private void DnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DnumberActionPerformed

    private void organActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organActionPerformed

    private void snActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    String name=Dname.getText();
    String id=sn.getText();
    String number=Dnumber.getText();
    String organs = organ.getText();
  
    
    int a = 0;
    if (id.equals("")){
        JOptionPane.showMessageDialog(null, "Sn IS MISSING.");
            a = 1;
    }
    if (name.equals("")){
        JOptionPane.showMessageDialog(null, "NAME IS MISSING.");
            a = 1;
    }
    if (number.equals("")){
        JOptionPane.showMessageDialog(null, "Contact IS MISSING.");
            a = 1;
    }
    if (organs.equals("")){
        JOptionPane.showMessageDialog(null, "Organ IS MISSING.");
            a = 1;
    }
    if (a==0){
        try{
            
            int Id=Integer.parseInt(id);
            double num=Double.parseDouble(number);
            donermodel d1= new donermodel(Id, name,num, organs);
//           drlistcontroller 
            donercontroller sc = new donercontroller();
            int insertdoner = sc.insertdetails(d1);

                if (insertdoner > 0) {
                    System.out.println("data inserted");
                } else {
                    System.out.println("Failed to insert data");
                }
                JOptionPane.showMessageDialog(null, "VALIDATION SUCCESSFUL");
                
            } 
        catch (Exception e) {
                // TODO: handle exception
                JOptionPane.showMessageDialog(null, e);
                System.out.printf(null,e);
            }
            
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DONERLISTFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DONERLISTFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DONERLISTFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DONERLISTFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DONERLISTFORM().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dname;
    private javax.swing.JTextField Dnumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField organ;
    private javax.swing.JTextField sn;
}
