/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author user
 */
public class emergencycontact extends javax.swing.JFrame {

    /**
     * Creates new form emergencycontact
     */
    public emergencycontact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel201 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        jLabel203 = new javax.swing.JLabel();
        jLabel204 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel205 = new javax.swing.JLabel();
        jLabel206 = new javax.swing.JLabel();
        jLabel207 = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jLabel211 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel212 = new javax.swing.JLabel();
        jLabel213 = new javax.swing.JLabel();
        jLabel214 = new javax.swing.JLabel();
        jLabel215 = new javax.swing.JLabel();
        jLabel216 = new javax.swing.JLabel();
        jLabel217 = new javax.swing.JLabel();
        jLabel218 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel219 = new javax.swing.JLabel();
        jLabel220 = new javax.swing.JLabel();
        jLabel221 = new javax.swing.JLabel();
        jLabel222 = new javax.swing.JLabel();
        jLabel223 = new javax.swing.JLabel();
        jLabel224 = new javax.swing.JLabel();
        jLabel225 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel226 = new javax.swing.JLabel();
        jLabel227 = new javax.swing.JLabel();
        jLabel228 = new javax.swing.JLabel();
        jLabel229 = new javax.swing.JLabel();
        jLabel230 = new javax.swing.JLabel();
        jLabel231 = new javax.swing.JLabel();
        jLabel232 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel233 = new javax.swing.JLabel();
        jLabel234 = new javax.swing.JLabel();
        jLabel235 = new javax.swing.JLabel();
        jLabel236 = new javax.swing.JLabel();
        jLabel237 = new javax.swing.JLabel();
        jLabel238 = new javax.swing.JLabel();
        jLabel239 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jLabel240 = new javax.swing.JLabel();
        jLabel241 = new javax.swing.JLabel();
        jLabel242 = new javax.swing.JLabel();
        jLabel243 = new javax.swing.JLabel();
        jLabel244 = new javax.swing.JLabel();
        jLabel245 = new javax.swing.JLabel();
        jLabel246 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel247 = new javax.swing.JLabel();
        jLabel248 = new javax.swing.JLabel();
        jLabel249 = new javax.swing.JLabel();
        jLabel250 = new javax.swing.JLabel();
        jLabel251 = new javax.swing.JLabel();
        jLabel252 = new javax.swing.JLabel();
        jLabel253 = new javax.swing.JLabel();
        jLabel254 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel157 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel164 = new javax.swing.JLabel();
        jLabel165 = new javax.swing.JLabel();
        jLabel166 = new javax.swing.JLabel();
        jLabel167 = new javax.swing.JLabel();
        jLabel168 = new javax.swing.JLabel();
        jLabel169 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel171 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        jLabel173 = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        jLabel175 = new javax.swing.JLabel();
        jLabel176 = new javax.swing.JLabel();
        jLabel177 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel178 = new javax.swing.JLabel();
        jLabel179 = new javax.swing.JLabel();
        jLabel180 = new javax.swing.JLabel();
        jLabel181 = new javax.swing.JLabel();
        jLabel182 = new javax.swing.JLabel();
        jLabel183 = new javax.swing.JLabel();
        jLabel184 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel185 = new javax.swing.JLabel();
        jLabel186 = new javax.swing.JLabel();
        jLabel187 = new javax.swing.JLabel();
        jLabel188 = new javax.swing.JLabel();
        jLabel189 = new javax.swing.JLabel();
        jLabel190 = new javax.swing.JLabel();
        jLabel191 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel192 = new javax.swing.JLabel();
        jLabel193 = new javax.swing.JLabel();
        jLabel194 = new javax.swing.JLabel();
        jLabel195 = new javax.swing.JLabel();
        jLabel196 = new javax.swing.JLabel();
        jLabel197 = new javax.swing.JLabel();
        jLabel198 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel200 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel199 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jLabel255 = new javax.swing.JLabel();
        jLabel256 = new javax.swing.JLabel();
        jLabel257 = new javax.swing.JLabel();
        jLabel258 = new javax.swing.JLabel();
        jLabel259 = new javax.swing.JLabel();
        jLabel260 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jLabel261 = new javax.swing.JLabel();
        jLabel262 = new javax.swing.JLabel();
        jLabel263 = new javax.swing.JLabel();
        jLabel264 = new javax.swing.JLabel();
        jLabel265 = new javax.swing.JLabel();
        jLabel266 = new javax.swing.JLabel();
        jLabel267 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jLabel268 = new javax.swing.JLabel();
        jLabel269 = new javax.swing.JLabel();
        jLabel270 = new javax.swing.JLabel();
        jLabel271 = new javax.swing.JLabel();
        jLabel272 = new javax.swing.JLabel();
        jLabel273 = new javax.swing.JLabel();
        jLabel274 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel275 = new javax.swing.JLabel();
        jLabel276 = new javax.swing.JLabel();
        jLabel277 = new javax.swing.JLabel();
        jLabel278 = new javax.swing.JLabel();
        jLabel279 = new javax.swing.JLabel();
        jLabel280 = new javax.swing.JLabel();
        jLabel281 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jLabel282 = new javax.swing.JLabel();
        jLabel283 = new javax.swing.JLabel();
        jLabel284 = new javax.swing.JLabel();
        jLabel285 = new javax.swing.JLabel();
        jLabel286 = new javax.swing.JLabel();
        jLabel287 = new javax.swing.JLabel();
        jLabel288 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jLabel289 = new javax.swing.JLabel();
        jLabel290 = new javax.swing.JLabel();
        jLabel291 = new javax.swing.JLabel();
        jLabel292 = new javax.swing.JLabel();
        jLabel293 = new javax.swing.JLabel();
        jLabel294 = new javax.swing.JLabel();
        jLabel295 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel296 = new javax.swing.JLabel();
        jLabel297 = new javax.swing.JLabel();
        jLabel298 = new javax.swing.JLabel();
        jLabel299 = new javax.swing.JLabel();
        jLabel300 = new javax.swing.JLabel();
        jLabel301 = new javax.swing.JLabel();
        jLabel302 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jLabel303 = new javax.swing.JLabel();
        jLabel304 = new javax.swing.JLabel();
        jLabel305 = new javax.swing.JLabel();
        jLabel306 = new javax.swing.JLabel();
        jLabel307 = new javax.swing.JLabel();
        jLabel308 = new javax.swing.JLabel();
        jLabel309 = new javax.swing.JLabel();
        jLabel310 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        jLabel311 = new javax.swing.JLabel();
        jLabel312 = new javax.swing.JLabel();
        jLabel313 = new javax.swing.JLabel();
        jLabel314 = new javax.swing.JLabel();
        jLabel315 = new javax.swing.JLabel();
        jLabel316 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jLabel317 = new javax.swing.JLabel();
        jLabel318 = new javax.swing.JLabel();
        jLabel319 = new javax.swing.JLabel();
        jLabel320 = new javax.swing.JLabel();
        jLabel321 = new javax.swing.JLabel();
        jLabel322 = new javax.swing.JLabel();
        jLabel323 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        jLabel324 = new javax.swing.JLabel();
        jLabel325 = new javax.swing.JLabel();
        jLabel326 = new javax.swing.JLabel();
        jLabel327 = new javax.swing.JLabel();
        jLabel328 = new javax.swing.JLabel();
        jLabel329 = new javax.swing.JLabel();
        jLabel330 = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        jLabel331 = new javax.swing.JLabel();
        jLabel332 = new javax.swing.JLabel();
        jLabel333 = new javax.swing.JLabel();
        jLabel334 = new javax.swing.JLabel();
        jLabel335 = new javax.swing.JLabel();
        jLabel336 = new javax.swing.JLabel();
        jLabel337 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        jLabel338 = new javax.swing.JLabel();
        jLabel339 = new javax.swing.JLabel();
        jLabel340 = new javax.swing.JLabel();
        jLabel341 = new javax.swing.JLabel();
        jLabel342 = new javax.swing.JLabel();
        jLabel343 = new javax.swing.JLabel();
        jLabel344 = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        jLabel345 = new javax.swing.JLabel();
        jLabel346 = new javax.swing.JLabel();
        jLabel347 = new javax.swing.JLabel();
        jLabel348 = new javax.swing.JLabel();
        jLabel349 = new javax.swing.JLabel();
        jLabel350 = new javax.swing.JLabel();
        jLabel351 = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        jLabel352 = new javax.swing.JLabel();
        jLabel353 = new javax.swing.JLabel();
        jLabel354 = new javax.swing.JLabel();
        jLabel355 = new javax.swing.JLabel();
        jLabel356 = new javax.swing.JLabel();
        jLabel357 = new javax.swing.JLabel();
        jLabel358 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jLabel359 = new javax.swing.JLabel();
        jLabel360 = new javax.swing.JLabel();
        jLabel361 = new javax.swing.JLabel();
        jLabel362 = new javax.swing.JLabel();
        jLabel363 = new javax.swing.JLabel();
        jLabel364 = new javax.swing.JLabel();
        jLabel365 = new javax.swing.JLabel();
        jLabel366 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 102, 255));

        jButton1.setText("LOGIN");

        jButton2.setText("ABOUT US");

        jButton3.setText("UPDATES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("HOME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(27, 27, 27)
                .addComponent(jButton3)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(680, 40, 420, 90);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Emergency Contact");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 0, 440, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(210, 150, 450, 70);

        jPanel3.setBackground(new java.awt.Color(153, 102, 255));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Goverment Health Center ");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(80, 10, 200, 20);

        jLabel4.setText("Contact:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 50, 50, 16);

        jLabel5.setText("Email:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 80, 32, 16);

        jLabel6.setText("Website :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 100, 60, 16);

        jLabel7.setText("01-5001245");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(110, 50, 120, 16);

        jLabel8.setText("govhealth@gmail.com");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(110, 80, 130, 16);

        jLabel9.setText("www.nphealth.com");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(110, 100, 110, 16);

        jPanel4.setBackground(new java.awt.Color(153, 102, 255));
        jPanel4.setLayout(null);

        jLabel10.setText("Goverment Health Center ");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(50, 10, 140, 16);

        jLabel11.setText("Contact:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(30, 60, 50, 16);

        jLabel12.setText("Email:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(30, 80, 32, 16);

        jLabel13.setText("website :");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(30, 100, 60, 16);

        jLabel14.setText("jLabel7");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(110, 50, 37, 16);

        jLabel15.setText("jLabel8");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(110, 80, 38, 16);

        jLabel16.setText("jLabel9");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(110, 100, 38, 16);

        jPanel5.setBackground(new java.awt.Color(153, 102, 255));
        jPanel5.setLayout(null);

        jLabel17.setText("Goverment Health Center ");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(50, 10, 140, 16);

        jLabel18.setText("Contact:");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(30, 60, 50, 16);

        jLabel19.setText("Email:");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(30, 80, 32, 16);

        jLabel20.setText("website :");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(30, 100, 60, 16);

        jLabel21.setText("jLabel7");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(110, 50, 37, 16);

        jLabel22.setText("jLabel8");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(110, 80, 38, 16);

        jLabel23.setText("jLabel9");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(110, 100, 38, 16);

        jPanel6.setBackground(new java.awt.Color(153, 102, 255));
        jPanel6.setLayout(null);

        jLabel24.setText("Goverment Health Center ");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(50, 10, 140, 16);

        jLabel25.setText("Contact:");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(30, 60, 50, 16);

        jLabel26.setText("Email:");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(30, 80, 32, 16);

        jLabel27.setText("website :");
        jPanel6.add(jLabel27);
        jLabel27.setBounds(30, 100, 60, 16);

        jLabel28.setText("jLabel7");
        jPanel6.add(jLabel28);
        jLabel28.setBounds(110, 50, 37, 16);

        jLabel29.setText("jLabel8");
        jPanel6.add(jLabel29);
        jLabel29.setBounds(110, 80, 38, 16);

        jLabel30.setText("jLabel9");
        jPanel6.add(jLabel30);
        jLabel30.setBounds(110, 100, 38, 16);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(110, 300, 240, 150);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(110, 300, 240, 150);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(110, 300, 240, 150);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(50, 250, 290, 150);

        jPanel7.setBackground(new java.awt.Color(153, 102, 255));
        jPanel7.setLayout(null);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setText("Rapid Health Service");
        jPanel7.add(jLabel31);
        jLabel31.setBounds(50, 10, 170, 20);

        jLabel32.setText("Contact:");
        jPanel7.add(jLabel32);
        jLabel32.setBounds(30, 50, 50, 16);

        jLabel33.setText("Email:");
        jPanel7.add(jLabel33);
        jLabel33.setBounds(30, 70, 32, 20);

        jLabel34.setText("Website :");
        jPanel7.add(jLabel34);
        jLabel34.setBounds(30, 90, 60, 16);

        jLabel36.setText("Rapidhealthnp@gmail.com");
        jPanel7.add(jLabel36);
        jLabel36.setBounds(110, 70, 150, 16);

        jLabel37.setText("www.Rapidhealth.np.com");
        jPanel7.add(jLabel37);
        jLabel37.setBounds(100, 80, 160, 30);

        jPanel8.setBackground(new java.awt.Color(153, 102, 255));
        jPanel8.setLayout(null);

        jLabel38.setText("Goverment Health Center ");
        jPanel8.add(jLabel38);
        jLabel38.setBounds(50, 10, 140, 16);

        jLabel39.setText("Contact:");
        jPanel8.add(jLabel39);
        jLabel39.setBounds(30, 60, 50, 16);

        jLabel40.setText("Email:");
        jPanel8.add(jLabel40);
        jLabel40.setBounds(30, 80, 32, 16);

        jLabel41.setText("website :");
        jPanel8.add(jLabel41);
        jLabel41.setBounds(30, 100, 60, 16);

        jLabel42.setText("jLabel7");
        jPanel8.add(jLabel42);
        jLabel42.setBounds(110, 50, 37, 16);

        jLabel43.setText("jLabel8");
        jPanel8.add(jLabel43);
        jLabel43.setBounds(110, 80, 38, 16);

        jLabel44.setText("jLabel9");
        jPanel8.add(jLabel44);
        jLabel44.setBounds(110, 100, 38, 16);

        jPanel9.setBackground(new java.awt.Color(153, 102, 255));
        jPanel9.setLayout(null);

        jLabel45.setText("Goverment Health Center ");
        jPanel9.add(jLabel45);
        jLabel45.setBounds(50, 10, 140, 16);

        jLabel46.setText("Contact:");
        jPanel9.add(jLabel46);
        jLabel46.setBounds(30, 60, 50, 16);

        jLabel47.setText("Email:");
        jPanel9.add(jLabel47);
        jLabel47.setBounds(30, 80, 32, 16);

        jLabel48.setText("website :");
        jPanel9.add(jLabel48);
        jLabel48.setBounds(30, 100, 60, 16);

        jLabel49.setText("jLabel7");
        jPanel9.add(jLabel49);
        jLabel49.setBounds(110, 50, 37, 16);

        jLabel50.setText("jLabel8");
        jPanel9.add(jLabel50);
        jLabel50.setBounds(110, 80, 38, 16);

        jLabel51.setText("jLabel9");
        jPanel9.add(jLabel51);
        jLabel51.setBounds(110, 100, 38, 16);

        jPanel10.setBackground(new java.awt.Color(153, 102, 255));
        jPanel10.setLayout(null);

        jLabel52.setText("Goverment Health Center ");
        jPanel10.add(jLabel52);
        jLabel52.setBounds(50, 10, 140, 16);

        jLabel53.setText("Contact:");
        jPanel10.add(jLabel53);
        jLabel53.setBounds(30, 60, 50, 16);

        jLabel54.setText("Email:");
        jPanel10.add(jLabel54);
        jLabel54.setBounds(30, 80, 32, 16);

        jLabel55.setText("website :");
        jPanel10.add(jLabel55);
        jLabel55.setBounds(30, 100, 60, 16);

        jLabel56.setText("jLabel7");
        jPanel10.add(jLabel56);
        jLabel56.setBounds(110, 50, 37, 16);

        jLabel57.setText("jLabel8");
        jPanel10.add(jLabel57);
        jLabel57.setBounds(110, 80, 38, 16);

        jLabel58.setText("jLabel9");
        jPanel10.add(jLabel58);
        jLabel58.setBounds(110, 100, 38, 16);

        jPanel9.add(jPanel10);
        jPanel10.setBounds(110, 300, 240, 150);

        jPanel8.add(jPanel9);
        jPanel9.setBounds(110, 300, 240, 150);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(110, 300, 240, 150);

        jPanel11.setBackground(new java.awt.Color(153, 102, 255));
        jPanel11.setLayout(null);

        jLabel59.setText("Goverment Health Center ");
        jPanel11.add(jLabel59);
        jLabel59.setBounds(50, 10, 140, 16);

        jLabel60.setText("Contact:");
        jPanel11.add(jLabel60);
        jLabel60.setBounds(30, 60, 50, 16);

        jLabel61.setText("Email:");
        jPanel11.add(jLabel61);
        jLabel61.setBounds(30, 80, 32, 16);

        jLabel62.setText("website :");
        jPanel11.add(jLabel62);
        jLabel62.setBounds(30, 100, 60, 16);

        jLabel63.setText("jLabel7");
        jPanel11.add(jLabel63);
        jLabel63.setBounds(110, 50, 37, 16);

        jLabel64.setText("jLabel8");
        jPanel11.add(jLabel64);
        jLabel64.setBounds(110, 80, 38, 16);

        jLabel65.setText("jLabel9");
        jPanel11.add(jLabel65);
        jLabel65.setBounds(110, 100, 38, 16);

        jPanel12.setBackground(new java.awt.Color(153, 102, 255));
        jPanel12.setLayout(null);

        jLabel66.setText("Goverment Health Center ");
        jPanel12.add(jLabel66);
        jLabel66.setBounds(50, 10, 140, 16);

        jLabel67.setText("Contact:");
        jPanel12.add(jLabel67);
        jLabel67.setBounds(30, 60, 50, 16);

        jLabel68.setText("Email:");
        jPanel12.add(jLabel68);
        jLabel68.setBounds(30, 80, 32, 16);

        jLabel69.setText("website :");
        jPanel12.add(jLabel69);
        jLabel69.setBounds(30, 100, 60, 16);

        jLabel70.setText("jLabel7");
        jPanel12.add(jLabel70);
        jLabel70.setBounds(110, 50, 37, 16);

        jLabel71.setText("jLabel8");
        jPanel12.add(jLabel71);
        jLabel71.setBounds(110, 80, 38, 16);

        jLabel72.setText("jLabel9");
        jPanel12.add(jLabel72);
        jLabel72.setBounds(110, 100, 38, 16);

        jPanel13.setBackground(new java.awt.Color(153, 102, 255));
        jPanel13.setLayout(null);

        jLabel73.setText("Goverment Health Center ");
        jPanel13.add(jLabel73);
        jLabel73.setBounds(50, 10, 140, 16);

        jLabel74.setText("Contact:");
        jPanel13.add(jLabel74);
        jLabel74.setBounds(30, 60, 50, 16);

        jLabel75.setText("Email:");
        jPanel13.add(jLabel75);
        jLabel75.setBounds(30, 80, 32, 16);

        jLabel76.setText("website :");
        jPanel13.add(jLabel76);
        jLabel76.setBounds(30, 100, 60, 16);

        jLabel77.setText("jLabel7");
        jPanel13.add(jLabel77);
        jLabel77.setBounds(110, 50, 37, 16);

        jLabel78.setText("jLabel8");
        jPanel13.add(jLabel78);
        jLabel78.setBounds(110, 80, 38, 16);

        jLabel79.setText("jLabel9");
        jPanel13.add(jLabel79);
        jLabel79.setBounds(110, 100, 38, 16);

        jPanel14.setBackground(new java.awt.Color(153, 102, 255));
        jPanel14.setLayout(null);

        jLabel80.setText("Goverment Health Center ");
        jPanel14.add(jLabel80);
        jLabel80.setBounds(50, 10, 140, 16);

        jLabel81.setText("Contact:");
        jPanel14.add(jLabel81);
        jLabel81.setBounds(30, 60, 50, 16);

        jLabel82.setText("Email:");
        jPanel14.add(jLabel82);
        jLabel82.setBounds(30, 80, 32, 16);

        jLabel83.setText("website :");
        jPanel14.add(jLabel83);
        jLabel83.setBounds(30, 100, 60, 16);

        jLabel84.setText("jLabel7");
        jPanel14.add(jLabel84);
        jLabel84.setBounds(110, 50, 37, 16);

        jLabel85.setText("jLabel8");
        jPanel14.add(jLabel85);
        jLabel85.setBounds(110, 80, 38, 16);

        jLabel86.setText("jLabel9");
        jPanel14.add(jLabel86);
        jLabel86.setBounds(110, 100, 38, 16);

        jPanel13.add(jPanel14);
        jPanel14.setBounds(110, 300, 240, 150);

        jPanel12.add(jPanel13);
        jPanel13.setBounds(110, 300, 240, 150);

        jPanel11.add(jPanel12);
        jPanel12.setBounds(110, 300, 240, 150);

        jPanel7.add(jPanel11);
        jPanel11.setBounds(230, 350, 240, 150);

        jLabel35.setText("01-5001245");
        jPanel7.add(jLabel35);
        jLabel35.setBounds(110, 50, 120, 16);

        jPanel31.setBackground(new java.awt.Color(153, 102, 255));
        jPanel31.setLayout(null);

        jLabel148.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel148.setText("Grande Hospital");
        jPanel31.add(jLabel148);
        jLabel148.setBounds(50, 10, 140, 20);

        jLabel149.setText("Contact:");
        jPanel31.add(jLabel149);
        jLabel149.setBounds(30, 50, 50, 16);

        jLabel201.setText("Email:");
        jPanel31.add(jLabel201);
        jLabel201.setBounds(30, 70, 32, 20);

        jLabel202.setText("Website :");
        jPanel31.add(jLabel202);
        jLabel202.setBounds(30, 90, 60, 16);

        jLabel203.setText("grandehospital@gmail.com");
        jPanel31.add(jLabel203);
        jLabel203.setBounds(110, 70, 150, 16);

        jLabel204.setText("www.GrandeHospital.np.com");
        jPanel31.add(jLabel204);
        jLabel204.setBounds(100, 80, 160, 30);

        jPanel32.setBackground(new java.awt.Color(153, 102, 255));
        jPanel32.setLayout(null);

        jLabel205.setText("Goverment Health Center ");
        jPanel32.add(jLabel205);
        jLabel205.setBounds(50, 10, 140, 16);

        jLabel206.setText("Contact:");
        jPanel32.add(jLabel206);
        jLabel206.setBounds(30, 60, 50, 16);

        jLabel207.setText("Email:");
        jPanel32.add(jLabel207);
        jLabel207.setBounds(30, 80, 32, 16);

        jLabel208.setText("website :");
        jPanel32.add(jLabel208);
        jLabel208.setBounds(30, 100, 60, 16);

        jLabel209.setText("jLabel7");
        jPanel32.add(jLabel209);
        jLabel209.setBounds(110, 50, 37, 16);

        jLabel210.setText("jLabel8");
        jPanel32.add(jLabel210);
        jLabel210.setBounds(110, 80, 38, 16);

        jLabel211.setText("jLabel9");
        jPanel32.add(jLabel211);
        jLabel211.setBounds(110, 100, 38, 16);

        jPanel33.setBackground(new java.awt.Color(153, 102, 255));
        jPanel33.setLayout(null);

        jLabel212.setText("Goverment Health Center ");
        jPanel33.add(jLabel212);
        jLabel212.setBounds(50, 10, 140, 16);

        jLabel213.setText("Contact:");
        jPanel33.add(jLabel213);
        jLabel213.setBounds(30, 60, 50, 16);

        jLabel214.setText("Email:");
        jPanel33.add(jLabel214);
        jLabel214.setBounds(30, 80, 32, 16);

        jLabel215.setText("website :");
        jPanel33.add(jLabel215);
        jLabel215.setBounds(30, 100, 60, 16);

        jLabel216.setText("jLabel7");
        jPanel33.add(jLabel216);
        jLabel216.setBounds(110, 50, 37, 16);

        jLabel217.setText("jLabel8");
        jPanel33.add(jLabel217);
        jLabel217.setBounds(110, 80, 38, 16);

        jLabel218.setText("jLabel9");
        jPanel33.add(jLabel218);
        jLabel218.setBounds(110, 100, 38, 16);

        jPanel34.setBackground(new java.awt.Color(153, 102, 255));
        jPanel34.setLayout(null);

        jLabel219.setText("Goverment Health Center ");
        jPanel34.add(jLabel219);
        jLabel219.setBounds(50, 10, 140, 16);

        jLabel220.setText("Contact:");
        jPanel34.add(jLabel220);
        jLabel220.setBounds(30, 60, 50, 16);

        jLabel221.setText("Email:");
        jPanel34.add(jLabel221);
        jLabel221.setBounds(30, 80, 32, 16);

        jLabel222.setText("website :");
        jPanel34.add(jLabel222);
        jLabel222.setBounds(30, 100, 60, 16);

        jLabel223.setText("jLabel7");
        jPanel34.add(jLabel223);
        jLabel223.setBounds(110, 50, 37, 16);

        jLabel224.setText("jLabel8");
        jPanel34.add(jLabel224);
        jLabel224.setBounds(110, 80, 38, 16);

        jLabel225.setText("jLabel9");
        jPanel34.add(jLabel225);
        jLabel225.setBounds(110, 100, 38, 16);

        jPanel33.add(jPanel34);
        jPanel34.setBounds(110, 300, 240, 150);

        jPanel32.add(jPanel33);
        jPanel33.setBounds(110, 300, 240, 150);

        jPanel31.add(jPanel32);
        jPanel32.setBounds(110, 300, 240, 150);

        jPanel35.setBackground(new java.awt.Color(153, 102, 255));
        jPanel35.setLayout(null);

        jLabel226.setText("Goverment Health Center ");
        jPanel35.add(jLabel226);
        jLabel226.setBounds(50, 10, 140, 16);

        jLabel227.setText("Contact:");
        jPanel35.add(jLabel227);
        jLabel227.setBounds(30, 60, 50, 16);

        jLabel228.setText("Email:");
        jPanel35.add(jLabel228);
        jLabel228.setBounds(30, 80, 32, 16);

        jLabel229.setText("website :");
        jPanel35.add(jLabel229);
        jLabel229.setBounds(30, 100, 60, 16);

        jLabel230.setText("jLabel7");
        jPanel35.add(jLabel230);
        jLabel230.setBounds(110, 50, 37, 16);

        jLabel231.setText("jLabel8");
        jPanel35.add(jLabel231);
        jLabel231.setBounds(110, 80, 38, 16);

        jLabel232.setText("jLabel9");
        jPanel35.add(jLabel232);
        jLabel232.setBounds(110, 100, 38, 16);

        jPanel36.setBackground(new java.awt.Color(153, 102, 255));
        jPanel36.setLayout(null);

        jLabel233.setText("Goverment Health Center ");
        jPanel36.add(jLabel233);
        jLabel233.setBounds(50, 10, 140, 16);

        jLabel234.setText("Contact:");
        jPanel36.add(jLabel234);
        jLabel234.setBounds(30, 60, 50, 16);

        jLabel235.setText("Email:");
        jPanel36.add(jLabel235);
        jLabel235.setBounds(30, 80, 32, 16);

        jLabel236.setText("website :");
        jPanel36.add(jLabel236);
        jLabel236.setBounds(30, 100, 60, 16);

        jLabel237.setText("jLabel7");
        jPanel36.add(jLabel237);
        jLabel237.setBounds(110, 50, 37, 16);

        jLabel238.setText("jLabel8");
        jPanel36.add(jLabel238);
        jLabel238.setBounds(110, 80, 38, 16);

        jLabel239.setText("jLabel9");
        jPanel36.add(jLabel239);
        jLabel239.setBounds(110, 100, 38, 16);

        jPanel37.setBackground(new java.awt.Color(153, 102, 255));
        jPanel37.setLayout(null);

        jLabel240.setText("Goverment Health Center ");
        jPanel37.add(jLabel240);
        jLabel240.setBounds(50, 10, 140, 16);

        jLabel241.setText("Contact:");
        jPanel37.add(jLabel241);
        jLabel241.setBounds(30, 60, 50, 16);

        jLabel242.setText("Email:");
        jPanel37.add(jLabel242);
        jLabel242.setBounds(30, 80, 32, 16);

        jLabel243.setText("website :");
        jPanel37.add(jLabel243);
        jLabel243.setBounds(30, 100, 60, 16);

        jLabel244.setText("jLabel7");
        jPanel37.add(jLabel244);
        jLabel244.setBounds(110, 50, 37, 16);

        jLabel245.setText("jLabel8");
        jPanel37.add(jLabel245);
        jLabel245.setBounds(110, 80, 38, 16);

        jLabel246.setText("jLabel9");
        jPanel37.add(jLabel246);
        jLabel246.setBounds(110, 100, 38, 16);

        jPanel38.setBackground(new java.awt.Color(153, 102, 255));
        jPanel38.setLayout(null);

        jLabel247.setText("Goverment Health Center ");
        jPanel38.add(jLabel247);
        jLabel247.setBounds(50, 10, 140, 16);

        jLabel248.setText("Contact:");
        jPanel38.add(jLabel248);
        jLabel248.setBounds(30, 60, 50, 16);

        jLabel249.setText("Email:");
        jPanel38.add(jLabel249);
        jLabel249.setBounds(30, 80, 32, 16);

        jLabel250.setText("website :");
        jPanel38.add(jLabel250);
        jLabel250.setBounds(30, 100, 60, 16);

        jLabel251.setText("jLabel7");
        jPanel38.add(jLabel251);
        jLabel251.setBounds(110, 50, 37, 16);

        jLabel252.setText("jLabel8");
        jPanel38.add(jLabel252);
        jLabel252.setBounds(110, 80, 38, 16);

        jLabel253.setText("jLabel9");
        jPanel38.add(jLabel253);
        jLabel253.setBounds(110, 100, 38, 16);

        jPanel37.add(jPanel38);
        jPanel38.setBounds(110, 300, 240, 150);

        jPanel36.add(jPanel37);
        jPanel37.setBounds(110, 300, 240, 150);

        jPanel35.add(jPanel36);
        jPanel36.setBounds(110, 300, 240, 150);

        jPanel31.add(jPanel35);
        jPanel35.setBounds(230, 350, 240, 150);

        jLabel254.setText("01-5001245");
        jPanel31.add(jLabel254);
        jLabel254.setBounds(110, 50, 120, 16);

        jPanel7.add(jPanel31);
        jPanel31.setBounds(540, 250, 270, 150);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(800, 250, 270, 150);

        jPanel23.setBackground(new java.awt.Color(153, 102, 255));
        jPanel23.setLayout(null);

        jLabel143.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel143.setText("Ambulance");
        jPanel23.add(jLabel143);
        jLabel143.setBounds(90, 20, 140, 16);

        jLabel144.setText("Contact:");
        jPanel23.add(jLabel144);
        jLabel144.setBounds(30, 50, 50, 16);

        jLabel145.setText("Contact");
        jPanel23.add(jLabel145);
        jLabel145.setBounds(30, 80, 70, 16);

        jLabel146.setText("contact :");
        jPanel23.add(jLabel146);
        jLabel146.setBounds(30, 100, 60, 16);

        jPanel24.setBackground(new java.awt.Color(153, 102, 255));
        jPanel24.setLayout(null);

        jLabel150.setText("Goverment Health Center ");
        jPanel24.add(jLabel150);
        jLabel150.setBounds(50, 10, 140, 16);

        jLabel151.setText("Contact:");
        jPanel24.add(jLabel151);
        jLabel151.setBounds(30, 60, 50, 16);

        jLabel152.setText("Email:");
        jPanel24.add(jLabel152);
        jLabel152.setBounds(30, 80, 32, 16);

        jLabel153.setText("website :");
        jPanel24.add(jLabel153);
        jLabel153.setBounds(30, 100, 60, 16);

        jLabel154.setText("jLabel7");
        jPanel24.add(jLabel154);
        jLabel154.setBounds(110, 50, 37, 16);

        jLabel155.setText("jLabel8");
        jPanel24.add(jLabel155);
        jLabel155.setBounds(110, 80, 38, 16);

        jLabel156.setText("jLabel9");
        jPanel24.add(jLabel156);
        jLabel156.setBounds(110, 100, 38, 16);

        jPanel25.setBackground(new java.awt.Color(153, 102, 255));
        jPanel25.setLayout(null);

        jLabel157.setText("Goverment Health Center ");
        jPanel25.add(jLabel157);
        jLabel157.setBounds(50, 10, 140, 16);

        jLabel158.setText("Contact:");
        jPanel25.add(jLabel158);
        jLabel158.setBounds(30, 60, 50, 16);

        jLabel159.setText("Email:");
        jPanel25.add(jLabel159);
        jLabel159.setBounds(30, 80, 32, 16);

        jLabel160.setText("website :");
        jPanel25.add(jLabel160);
        jLabel160.setBounds(30, 100, 60, 16);

        jLabel161.setText("jLabel7");
        jPanel25.add(jLabel161);
        jLabel161.setBounds(110, 50, 37, 16);

        jLabel162.setText("jLabel8");
        jPanel25.add(jLabel162);
        jLabel162.setBounds(110, 80, 38, 16);

        jLabel163.setText("jLabel9");
        jPanel25.add(jLabel163);
        jLabel163.setBounds(110, 100, 38, 16);

        jPanel26.setBackground(new java.awt.Color(153, 102, 255));
        jPanel26.setLayout(null);

        jLabel164.setText("Goverment Health Center ");
        jPanel26.add(jLabel164);
        jLabel164.setBounds(50, 10, 140, 16);

        jLabel165.setText("Contact:");
        jPanel26.add(jLabel165);
        jLabel165.setBounds(30, 60, 50, 16);

        jLabel166.setText("Email:");
        jPanel26.add(jLabel166);
        jLabel166.setBounds(30, 80, 32, 16);

        jLabel167.setText("website :");
        jPanel26.add(jLabel167);
        jLabel167.setBounds(30, 100, 60, 16);

        jLabel168.setText("jLabel7");
        jPanel26.add(jLabel168);
        jLabel168.setBounds(110, 50, 37, 16);

        jLabel169.setText("jLabel8");
        jPanel26.add(jLabel169);
        jLabel169.setBounds(110, 80, 38, 16);

        jLabel170.setText("jLabel9");
        jPanel26.add(jLabel170);
        jLabel170.setBounds(110, 100, 38, 16);

        jPanel25.add(jPanel26);
        jPanel26.setBounds(110, 300, 240, 150);

        jPanel24.add(jPanel25);
        jPanel25.setBounds(110, 300, 240, 150);

        jPanel23.add(jPanel24);
        jPanel24.setBounds(110, 300, 240, 150);

        jPanel27.setBackground(new java.awt.Color(153, 102, 255));
        jPanel27.setLayout(null);

        jLabel171.setText("Goverment Health Center ");
        jPanel27.add(jLabel171);
        jLabel171.setBounds(50, 10, 140, 16);

        jLabel172.setText("Contact:");
        jPanel27.add(jLabel172);
        jLabel172.setBounds(30, 60, 50, 16);

        jLabel173.setText("Email:");
        jPanel27.add(jLabel173);
        jLabel173.setBounds(30, 80, 32, 16);

        jLabel174.setText("website :");
        jPanel27.add(jLabel174);
        jLabel174.setBounds(30, 100, 60, 16);

        jLabel175.setText("jLabel7");
        jPanel27.add(jLabel175);
        jLabel175.setBounds(110, 50, 37, 16);

        jLabel176.setText("jLabel8");
        jPanel27.add(jLabel176);
        jLabel176.setBounds(110, 80, 38, 16);

        jLabel177.setText("jLabel9");
        jPanel27.add(jLabel177);
        jLabel177.setBounds(110, 100, 38, 16);

        jPanel28.setBackground(new java.awt.Color(153, 102, 255));
        jPanel28.setLayout(null);

        jLabel178.setText("Goverment Health Center ");
        jPanel28.add(jLabel178);
        jLabel178.setBounds(50, 10, 140, 16);

        jLabel179.setText("Contact:");
        jPanel28.add(jLabel179);
        jLabel179.setBounds(30, 60, 50, 16);

        jLabel180.setText("Email:");
        jPanel28.add(jLabel180);
        jLabel180.setBounds(30, 80, 32, 16);

        jLabel181.setText("website :");
        jPanel28.add(jLabel181);
        jLabel181.setBounds(30, 100, 60, 16);

        jLabel182.setText("jLabel7");
        jPanel28.add(jLabel182);
        jLabel182.setBounds(110, 50, 37, 16);

        jLabel183.setText("jLabel8");
        jPanel28.add(jLabel183);
        jLabel183.setBounds(110, 80, 38, 16);

        jLabel184.setText("jLabel9");
        jPanel28.add(jLabel184);
        jLabel184.setBounds(110, 100, 38, 16);

        jPanel29.setBackground(new java.awt.Color(153, 102, 255));
        jPanel29.setLayout(null);

        jLabel185.setText("Goverment Health Center ");
        jPanel29.add(jLabel185);
        jLabel185.setBounds(50, 10, 140, 16);

        jLabel186.setText("Contact:");
        jPanel29.add(jLabel186);
        jLabel186.setBounds(30, 60, 50, 16);

        jLabel187.setText("Email:");
        jPanel29.add(jLabel187);
        jLabel187.setBounds(30, 80, 32, 16);

        jLabel188.setText("website :");
        jPanel29.add(jLabel188);
        jLabel188.setBounds(30, 100, 60, 16);

        jLabel189.setText("jLabel7");
        jPanel29.add(jLabel189);
        jLabel189.setBounds(110, 50, 37, 16);

        jLabel190.setText("jLabel8");
        jPanel29.add(jLabel190);
        jLabel190.setBounds(110, 80, 38, 16);

        jLabel191.setText("jLabel9");
        jPanel29.add(jLabel191);
        jLabel191.setBounds(110, 100, 38, 16);

        jPanel30.setBackground(new java.awt.Color(153, 102, 255));
        jPanel30.setLayout(null);

        jLabel192.setText("Goverment Health Center ");
        jPanel30.add(jLabel192);
        jLabel192.setBounds(50, 10, 140, 16);

        jLabel193.setText("Contact:");
        jPanel30.add(jLabel193);
        jLabel193.setBounds(30, 60, 50, 16);

        jLabel194.setText("Email:");
        jPanel30.add(jLabel194);
        jLabel194.setBounds(30, 80, 32, 16);

        jLabel195.setText("website :");
        jPanel30.add(jLabel195);
        jLabel195.setBounds(30, 100, 60, 16);

        jLabel196.setText("jLabel7");
        jPanel30.add(jLabel196);
        jLabel196.setBounds(110, 50, 37, 16);

        jLabel197.setText("jLabel8");
        jPanel30.add(jLabel197);
        jLabel197.setBounds(110, 80, 38, 16);

        jLabel198.setText("jLabel9");
        jPanel30.add(jLabel198);
        jLabel198.setBounds(110, 100, 38, 16);

        jPanel29.add(jPanel30);
        jPanel30.setBounds(110, 300, 240, 150);

        jPanel28.add(jPanel29);
        jPanel29.setBounds(110, 300, 240, 150);

        jPanel27.add(jPanel28);
        jPanel28.setBounds(110, 300, 240, 150);

        jPanel23.add(jPanel27);
        jPanel27.setBounds(230, 350, 240, 150);

        jLabel91.setText("01-5001245");
        jPanel23.add(jLabel91);
        jLabel91.setBounds(100, 50, 120, 16);

        jLabel147.setText("01-5001245");
        jPanel23.add(jLabel147);
        jLabel147.setBounds(100, 80, 120, 16);

        jLabel200.setText("01-5001245");
        jPanel23.add(jLabel200);
        jLabel200.setBounds(100, 100, 120, 16);

        getContentPane().add(jPanel23);
        jPanel23.setBounds(220, 430, 290, 150);

        jPanel15.setBackground(new java.awt.Color(153, 102, 255));
        jPanel15.setLayout(null);

        jLabel87.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel87.setText("Bhaktpur  Hospital");
        jPanel15.add(jLabel87);
        jLabel87.setBounds(80, 20, 140, 16);

        jLabel88.setText("Contact:");
        jPanel15.add(jLabel88);
        jLabel88.setBounds(30, 50, 50, 16);

        jLabel89.setText("Email:");
        jPanel15.add(jLabel89);
        jLabel89.setBounds(30, 70, 32, 16);

        jLabel90.setText("website :");
        jPanel15.add(jLabel90);
        jLabel90.setBounds(30, 90, 60, 16);

        jLabel92.setText("bhaktpurhospital@gmail.com");
        jPanel15.add(jLabel92);
        jLabel92.setBounds(100, 70, 180, 16);

        jLabel93.setText("www.bhaktpurhospital.com");
        jPanel15.add(jLabel93);
        jLabel93.setBounds(100, 90, 147, 16);

        jPanel16.setBackground(new java.awt.Color(153, 102, 255));
        jPanel16.setLayout(null);

        jLabel94.setText("Goverment Health Center ");
        jPanel16.add(jLabel94);
        jLabel94.setBounds(50, 10, 140, 16);

        jLabel95.setText("Contact:");
        jPanel16.add(jLabel95);
        jLabel95.setBounds(30, 60, 50, 16);

        jLabel96.setText("Email:");
        jPanel16.add(jLabel96);
        jLabel96.setBounds(30, 80, 32, 16);

        jLabel97.setText("website :");
        jPanel16.add(jLabel97);
        jLabel97.setBounds(30, 100, 60, 16);

        jLabel98.setText("jLabel7");
        jPanel16.add(jLabel98);
        jLabel98.setBounds(110, 50, 37, 16);

        jLabel99.setText("jLabel8");
        jPanel16.add(jLabel99);
        jLabel99.setBounds(110, 80, 38, 16);

        jLabel100.setText("jLabel9");
        jPanel16.add(jLabel100);
        jLabel100.setBounds(110, 100, 38, 16);

        jPanel17.setBackground(new java.awt.Color(153, 102, 255));
        jPanel17.setLayout(null);

        jLabel101.setText("Goverment Health Center ");
        jPanel17.add(jLabel101);
        jLabel101.setBounds(50, 10, 140, 16);

        jLabel102.setText("Contact:");
        jPanel17.add(jLabel102);
        jLabel102.setBounds(30, 60, 50, 16);

        jLabel103.setText("Email:");
        jPanel17.add(jLabel103);
        jLabel103.setBounds(30, 80, 32, 16);

        jLabel104.setText("website :");
        jPanel17.add(jLabel104);
        jLabel104.setBounds(30, 100, 60, 16);

        jLabel105.setText("jLabel7");
        jPanel17.add(jLabel105);
        jLabel105.setBounds(110, 50, 37, 16);

        jLabel106.setText("jLabel8");
        jPanel17.add(jLabel106);
        jLabel106.setBounds(110, 80, 38, 16);

        jLabel107.setText("jLabel9");
        jPanel17.add(jLabel107);
        jLabel107.setBounds(110, 100, 38, 16);

        jPanel18.setBackground(new java.awt.Color(153, 102, 255));
        jPanel18.setLayout(null);

        jLabel108.setText("Goverment Health Center ");
        jPanel18.add(jLabel108);
        jLabel108.setBounds(50, 10, 140, 16);

        jLabel109.setText("Contact:");
        jPanel18.add(jLabel109);
        jLabel109.setBounds(30, 60, 50, 16);

        jLabel110.setText("Email:");
        jPanel18.add(jLabel110);
        jLabel110.setBounds(30, 80, 32, 16);

        jLabel111.setText("website :");
        jPanel18.add(jLabel111);
        jLabel111.setBounds(30, 100, 60, 16);

        jLabel112.setText("jLabel7");
        jPanel18.add(jLabel112);
        jLabel112.setBounds(110, 50, 37, 16);

        jLabel113.setText("jLabel8");
        jPanel18.add(jLabel113);
        jLabel113.setBounds(110, 80, 38, 16);

        jLabel114.setText("jLabel9");
        jPanel18.add(jLabel114);
        jLabel114.setBounds(110, 100, 38, 16);

        jPanel17.add(jPanel18);
        jPanel18.setBounds(110, 300, 240, 150);

        jPanel16.add(jPanel17);
        jPanel17.setBounds(110, 300, 240, 150);

        jPanel15.add(jPanel16);
        jPanel16.setBounds(110, 300, 240, 150);

        jPanel19.setBackground(new java.awt.Color(153, 102, 255));
        jPanel19.setLayout(null);

        jLabel115.setText("Goverment Health Center ");
        jPanel19.add(jLabel115);
        jLabel115.setBounds(50, 10, 140, 16);

        jLabel116.setText("Contact:");
        jPanel19.add(jLabel116);
        jLabel116.setBounds(30, 60, 50, 16);

        jLabel117.setText("Email:");
        jPanel19.add(jLabel117);
        jLabel117.setBounds(30, 80, 32, 16);

        jLabel118.setText("website :");
        jPanel19.add(jLabel118);
        jLabel118.setBounds(30, 100, 60, 16);

        jLabel119.setText("jLabel7");
        jPanel19.add(jLabel119);
        jLabel119.setBounds(110, 50, 37, 16);

        jLabel120.setText("jLabel8");
        jPanel19.add(jLabel120);
        jLabel120.setBounds(110, 80, 38, 16);

        jLabel121.setText("jLabel9");
        jPanel19.add(jLabel121);
        jLabel121.setBounds(110, 100, 38, 16);

        jPanel20.setBackground(new java.awt.Color(153, 102, 255));
        jPanel20.setLayout(null);

        jLabel122.setText("Goverment Health Center ");
        jPanel20.add(jLabel122);
        jLabel122.setBounds(50, 10, 140, 16);

        jLabel123.setText("Contact:");
        jPanel20.add(jLabel123);
        jLabel123.setBounds(30, 60, 50, 16);

        jLabel124.setText("Email:");
        jPanel20.add(jLabel124);
        jLabel124.setBounds(30, 80, 32, 16);

        jLabel125.setText("website :");
        jPanel20.add(jLabel125);
        jLabel125.setBounds(30, 100, 60, 16);

        jLabel126.setText("jLabel7");
        jPanel20.add(jLabel126);
        jLabel126.setBounds(110, 50, 37, 16);

        jLabel127.setText("jLabel8");
        jPanel20.add(jLabel127);
        jLabel127.setBounds(110, 80, 38, 16);

        jLabel128.setText("jLabel9");
        jPanel20.add(jLabel128);
        jLabel128.setBounds(110, 100, 38, 16);

        jPanel21.setBackground(new java.awt.Color(153, 102, 255));
        jPanel21.setLayout(null);

        jLabel129.setText("Goverment Health Center ");
        jPanel21.add(jLabel129);
        jLabel129.setBounds(50, 10, 140, 16);

        jLabel130.setText("Contact:");
        jPanel21.add(jLabel130);
        jLabel130.setBounds(30, 60, 50, 16);

        jLabel131.setText("Email:");
        jPanel21.add(jLabel131);
        jLabel131.setBounds(30, 80, 32, 16);

        jLabel132.setText("website :");
        jPanel21.add(jLabel132);
        jLabel132.setBounds(30, 100, 60, 16);

        jLabel133.setText("jLabel7");
        jPanel21.add(jLabel133);
        jLabel133.setBounds(110, 50, 37, 16);

        jLabel134.setText("jLabel8");
        jPanel21.add(jLabel134);
        jLabel134.setBounds(110, 80, 38, 16);

        jLabel135.setText("jLabel9");
        jPanel21.add(jLabel135);
        jLabel135.setBounds(110, 100, 38, 16);

        jPanel22.setBackground(new java.awt.Color(153, 102, 255));
        jPanel22.setLayout(null);

        jLabel136.setText("Goverment Health Center ");
        jPanel22.add(jLabel136);
        jLabel136.setBounds(50, 10, 140, 16);

        jLabel137.setText("Contact:");
        jPanel22.add(jLabel137);
        jLabel137.setBounds(30, 60, 50, 16);

        jLabel138.setText("Email:");
        jPanel22.add(jLabel138);
        jLabel138.setBounds(30, 80, 32, 16);

        jLabel139.setText("website :");
        jPanel22.add(jLabel139);
        jLabel139.setBounds(30, 100, 60, 16);

        jLabel140.setText("jLabel7");
        jPanel22.add(jLabel140);
        jLabel140.setBounds(110, 50, 37, 16);

        jLabel141.setText("jLabel8");
        jPanel22.add(jLabel141);
        jLabel141.setBounds(110, 80, 38, 16);

        jLabel142.setText("jLabel9");
        jPanel22.add(jLabel142);
        jLabel142.setBounds(110, 100, 38, 16);

        jPanel21.add(jPanel22);
        jPanel22.setBounds(110, 300, 240, 150);

        jPanel20.add(jPanel21);
        jPanel21.setBounds(110, 300, 240, 150);

        jPanel19.add(jPanel20);
        jPanel20.setBounds(110, 300, 240, 150);

        jPanel15.add(jPanel19);
        jPanel19.setBounds(230, 350, 240, 150);

        jLabel199.setText("01-5001245");
        jPanel15.add(jLabel199);
        jLabel199.setBounds(100, 50, 120, 16);

        getContentPane().add(jPanel15);
        jPanel15.setBounds(660, 430, 290, 150);

        jPanel39.setBackground(new java.awt.Color(153, 102, 255));
        jPanel39.setLayout(null);

        jLabel255.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel255.setText("Grande Hospital");
        jPanel39.add(jLabel255);
        jLabel255.setBounds(50, 10, 140, 20);

        jLabel256.setText("Contact:");
        jPanel39.add(jLabel256);
        jLabel256.setBounds(30, 50, 50, 16);

        jLabel257.setText("Email:");
        jPanel39.add(jLabel257);
        jLabel257.setBounds(30, 70, 32, 20);

        jLabel258.setText("Website :");
        jPanel39.add(jLabel258);
        jLabel258.setBounds(30, 90, 60, 16);

        jLabel259.setText("grandehospital@gmail.com");
        jPanel39.add(jLabel259);
        jLabel259.setBounds(110, 70, 150, 16);

        jLabel260.setText("www.GrandeHospital.np.com");
        jPanel39.add(jLabel260);
        jLabel260.setBounds(100, 80, 160, 30);

        jPanel40.setBackground(new java.awt.Color(153, 102, 255));
        jPanel40.setLayout(null);

        jLabel261.setText("Goverment Health Center ");
        jPanel40.add(jLabel261);
        jLabel261.setBounds(50, 10, 140, 16);

        jLabel262.setText("Contact:");
        jPanel40.add(jLabel262);
        jLabel262.setBounds(30, 60, 50, 16);

        jLabel263.setText("Email:");
        jPanel40.add(jLabel263);
        jLabel263.setBounds(30, 80, 32, 16);

        jLabel264.setText("website :");
        jPanel40.add(jLabel264);
        jLabel264.setBounds(30, 100, 60, 16);

        jLabel265.setText("jLabel7");
        jPanel40.add(jLabel265);
        jLabel265.setBounds(110, 50, 37, 16);

        jLabel266.setText("jLabel8");
        jPanel40.add(jLabel266);
        jLabel266.setBounds(110, 80, 38, 16);

        jLabel267.setText("jLabel9");
        jPanel40.add(jLabel267);
        jLabel267.setBounds(110, 100, 38, 16);

        jPanel41.setBackground(new java.awt.Color(153, 102, 255));
        jPanel41.setLayout(null);

        jLabel268.setText("Goverment Health Center ");
        jPanel41.add(jLabel268);
        jLabel268.setBounds(50, 10, 140, 16);

        jLabel269.setText("Contact:");
        jPanel41.add(jLabel269);
        jLabel269.setBounds(30, 60, 50, 16);

        jLabel270.setText("Email:");
        jPanel41.add(jLabel270);
        jLabel270.setBounds(30, 80, 32, 16);

        jLabel271.setText("website :");
        jPanel41.add(jLabel271);
        jLabel271.setBounds(30, 100, 60, 16);

        jLabel272.setText("jLabel7");
        jPanel41.add(jLabel272);
        jLabel272.setBounds(110, 50, 37, 16);

        jLabel273.setText("jLabel8");
        jPanel41.add(jLabel273);
        jLabel273.setBounds(110, 80, 38, 16);

        jLabel274.setText("jLabel9");
        jPanel41.add(jLabel274);
        jLabel274.setBounds(110, 100, 38, 16);

        jPanel42.setBackground(new java.awt.Color(153, 102, 255));
        jPanel42.setLayout(null);

        jLabel275.setText("Goverment Health Center ");
        jPanel42.add(jLabel275);
        jLabel275.setBounds(50, 10, 140, 16);

        jLabel276.setText("Contact:");
        jPanel42.add(jLabel276);
        jLabel276.setBounds(30, 60, 50, 16);

        jLabel277.setText("Email:");
        jPanel42.add(jLabel277);
        jLabel277.setBounds(30, 80, 32, 16);

        jLabel278.setText("website :");
        jPanel42.add(jLabel278);
        jLabel278.setBounds(30, 100, 60, 16);

        jLabel279.setText("jLabel7");
        jPanel42.add(jLabel279);
        jLabel279.setBounds(110, 50, 37, 16);

        jLabel280.setText("jLabel8");
        jPanel42.add(jLabel280);
        jLabel280.setBounds(110, 80, 38, 16);

        jLabel281.setText("jLabel9");
        jPanel42.add(jLabel281);
        jLabel281.setBounds(110, 100, 38, 16);

        jPanel41.add(jPanel42);
        jPanel42.setBounds(110, 300, 240, 150);

        jPanel40.add(jPanel41);
        jPanel41.setBounds(110, 300, 240, 150);

        jPanel39.add(jPanel40);
        jPanel40.setBounds(110, 300, 240, 150);

        jPanel43.setBackground(new java.awt.Color(153, 102, 255));
        jPanel43.setLayout(null);

        jLabel282.setText("Goverment Health Center ");
        jPanel43.add(jLabel282);
        jLabel282.setBounds(50, 10, 140, 16);

        jLabel283.setText("Contact:");
        jPanel43.add(jLabel283);
        jLabel283.setBounds(30, 60, 50, 16);

        jLabel284.setText("Email:");
        jPanel43.add(jLabel284);
        jLabel284.setBounds(30, 80, 32, 16);

        jLabel285.setText("website :");
        jPanel43.add(jLabel285);
        jLabel285.setBounds(30, 100, 60, 16);

        jLabel286.setText("jLabel7");
        jPanel43.add(jLabel286);
        jLabel286.setBounds(110, 50, 37, 16);

        jLabel287.setText("jLabel8");
        jPanel43.add(jLabel287);
        jLabel287.setBounds(110, 80, 38, 16);

        jLabel288.setText("jLabel9");
        jPanel43.add(jLabel288);
        jLabel288.setBounds(110, 100, 38, 16);

        jPanel44.setBackground(new java.awt.Color(153, 102, 255));
        jPanel44.setLayout(null);

        jLabel289.setText("Goverment Health Center ");
        jPanel44.add(jLabel289);
        jLabel289.setBounds(50, 10, 140, 16);

        jLabel290.setText("Contact:");
        jPanel44.add(jLabel290);
        jLabel290.setBounds(30, 60, 50, 16);

        jLabel291.setText("Email:");
        jPanel44.add(jLabel291);
        jLabel291.setBounds(30, 80, 32, 16);

        jLabel292.setText("website :");
        jPanel44.add(jLabel292);
        jLabel292.setBounds(30, 100, 60, 16);

        jLabel293.setText("jLabel7");
        jPanel44.add(jLabel293);
        jLabel293.setBounds(110, 50, 37, 16);

        jLabel294.setText("jLabel8");
        jPanel44.add(jLabel294);
        jLabel294.setBounds(110, 80, 38, 16);

        jLabel295.setText("jLabel9");
        jPanel44.add(jLabel295);
        jLabel295.setBounds(110, 100, 38, 16);

        jPanel45.setBackground(new java.awt.Color(153, 102, 255));
        jPanel45.setLayout(null);

        jLabel296.setText("Goverment Health Center ");
        jPanel45.add(jLabel296);
        jLabel296.setBounds(50, 10, 140, 16);

        jLabel297.setText("Contact:");
        jPanel45.add(jLabel297);
        jLabel297.setBounds(30, 60, 50, 16);

        jLabel298.setText("Email:");
        jPanel45.add(jLabel298);
        jLabel298.setBounds(30, 80, 32, 16);

        jLabel299.setText("website :");
        jPanel45.add(jLabel299);
        jLabel299.setBounds(30, 100, 60, 16);

        jLabel300.setText("jLabel7");
        jPanel45.add(jLabel300);
        jLabel300.setBounds(110, 50, 37, 16);

        jLabel301.setText("jLabel8");
        jPanel45.add(jLabel301);
        jLabel301.setBounds(110, 80, 38, 16);

        jLabel302.setText("jLabel9");
        jPanel45.add(jLabel302);
        jLabel302.setBounds(110, 100, 38, 16);

        jPanel46.setBackground(new java.awt.Color(153, 102, 255));
        jPanel46.setLayout(null);

        jLabel303.setText("Goverment Health Center ");
        jPanel46.add(jLabel303);
        jLabel303.setBounds(50, 10, 140, 16);

        jLabel304.setText("Contact:");
        jPanel46.add(jLabel304);
        jLabel304.setBounds(30, 60, 50, 16);

        jLabel305.setText("Email:");
        jPanel46.add(jLabel305);
        jLabel305.setBounds(30, 80, 32, 16);

        jLabel306.setText("website :");
        jPanel46.add(jLabel306);
        jLabel306.setBounds(30, 100, 60, 16);

        jLabel307.setText("jLabel7");
        jPanel46.add(jLabel307);
        jLabel307.setBounds(110, 50, 37, 16);

        jLabel308.setText("jLabel8");
        jPanel46.add(jLabel308);
        jLabel308.setBounds(110, 80, 38, 16);

        jLabel309.setText("jLabel9");
        jPanel46.add(jLabel309);
        jLabel309.setBounds(110, 100, 38, 16);

        jPanel45.add(jPanel46);
        jPanel46.setBounds(110, 300, 240, 150);

        jPanel44.add(jPanel45);
        jPanel45.setBounds(110, 300, 240, 150);

        jPanel43.add(jPanel44);
        jPanel44.setBounds(110, 300, 240, 150);

        jPanel39.add(jPanel43);
        jPanel43.setBounds(230, 350, 240, 150);

        jLabel310.setText("01-5001245");
        jPanel39.add(jLabel310);
        jLabel310.setBounds(110, 50, 120, 16);

        jPanel47.setBackground(new java.awt.Color(153, 102, 255));
        jPanel47.setLayout(null);

        jLabel311.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel311.setText("Grande Hospital");
        jPanel47.add(jLabel311);
        jLabel311.setBounds(50, 10, 140, 20);

        jLabel312.setText("Contact:");
        jPanel47.add(jLabel312);
        jLabel312.setBounds(30, 50, 50, 16);

        jLabel313.setText("Email:");
        jPanel47.add(jLabel313);
        jLabel313.setBounds(30, 70, 32, 20);

        jLabel314.setText("Website :");
        jPanel47.add(jLabel314);
        jLabel314.setBounds(30, 90, 60, 16);

        jLabel315.setText("grandehospital@gmail.com");
        jPanel47.add(jLabel315);
        jLabel315.setBounds(110, 70, 150, 16);

        jLabel316.setText("www.GrandeHospital.np.com");
        jPanel47.add(jLabel316);
        jLabel316.setBounds(100, 80, 160, 30);

        jPanel48.setBackground(new java.awt.Color(153, 102, 255));
        jPanel48.setLayout(null);

        jLabel317.setText("Goverment Health Center ");
        jPanel48.add(jLabel317);
        jLabel317.setBounds(50, 10, 140, 16);

        jLabel318.setText("Contact:");
        jPanel48.add(jLabel318);
        jLabel318.setBounds(30, 60, 50, 16);

        jLabel319.setText("Email:");
        jPanel48.add(jLabel319);
        jLabel319.setBounds(30, 80, 32, 16);

        jLabel320.setText("website :");
        jPanel48.add(jLabel320);
        jLabel320.setBounds(30, 100, 60, 16);

        jLabel321.setText("jLabel7");
        jPanel48.add(jLabel321);
        jLabel321.setBounds(110, 50, 37, 16);

        jLabel322.setText("jLabel8");
        jPanel48.add(jLabel322);
        jLabel322.setBounds(110, 80, 38, 16);

        jLabel323.setText("jLabel9");
        jPanel48.add(jLabel323);
        jLabel323.setBounds(110, 100, 38, 16);

        jPanel49.setBackground(new java.awt.Color(153, 102, 255));
        jPanel49.setLayout(null);

        jLabel324.setText("Goverment Health Center ");
        jPanel49.add(jLabel324);
        jLabel324.setBounds(50, 10, 140, 16);

        jLabel325.setText("Contact:");
        jPanel49.add(jLabel325);
        jLabel325.setBounds(30, 60, 50, 16);

        jLabel326.setText("Email:");
        jPanel49.add(jLabel326);
        jLabel326.setBounds(30, 80, 32, 16);

        jLabel327.setText("website :");
        jPanel49.add(jLabel327);
        jLabel327.setBounds(30, 100, 60, 16);

        jLabel328.setText("jLabel7");
        jPanel49.add(jLabel328);
        jLabel328.setBounds(110, 50, 37, 16);

        jLabel329.setText("jLabel8");
        jPanel49.add(jLabel329);
        jLabel329.setBounds(110, 80, 38, 16);

        jLabel330.setText("jLabel9");
        jPanel49.add(jLabel330);
        jLabel330.setBounds(110, 100, 38, 16);

        jPanel50.setBackground(new java.awt.Color(153, 102, 255));
        jPanel50.setLayout(null);

        jLabel331.setText("Goverment Health Center ");
        jPanel50.add(jLabel331);
        jLabel331.setBounds(50, 10, 140, 16);

        jLabel332.setText("Contact:");
        jPanel50.add(jLabel332);
        jLabel332.setBounds(30, 60, 50, 16);

        jLabel333.setText("Email:");
        jPanel50.add(jLabel333);
        jLabel333.setBounds(30, 80, 32, 16);

        jLabel334.setText("website :");
        jPanel50.add(jLabel334);
        jLabel334.setBounds(30, 100, 60, 16);

        jLabel335.setText("jLabel7");
        jPanel50.add(jLabel335);
        jLabel335.setBounds(110, 50, 37, 16);

        jLabel336.setText("jLabel8");
        jPanel50.add(jLabel336);
        jLabel336.setBounds(110, 80, 38, 16);

        jLabel337.setText("jLabel9");
        jPanel50.add(jLabel337);
        jLabel337.setBounds(110, 100, 38, 16);

        jPanel49.add(jPanel50);
        jPanel50.setBounds(110, 300, 240, 150);

        jPanel48.add(jPanel49);
        jPanel49.setBounds(110, 300, 240, 150);

        jPanel47.add(jPanel48);
        jPanel48.setBounds(110, 300, 240, 150);

        jPanel51.setBackground(new java.awt.Color(153, 102, 255));
        jPanel51.setLayout(null);

        jLabel338.setText("Goverment Health Center ");
        jPanel51.add(jLabel338);
        jLabel338.setBounds(50, 10, 140, 16);

        jLabel339.setText("Contact:");
        jPanel51.add(jLabel339);
        jLabel339.setBounds(30, 60, 50, 16);

        jLabel340.setText("Email:");
        jPanel51.add(jLabel340);
        jLabel340.setBounds(30, 80, 32, 16);

        jLabel341.setText("website :");
        jPanel51.add(jLabel341);
        jLabel341.setBounds(30, 100, 60, 16);

        jLabel342.setText("jLabel7");
        jPanel51.add(jLabel342);
        jLabel342.setBounds(110, 50, 37, 16);

        jLabel343.setText("jLabel8");
        jPanel51.add(jLabel343);
        jLabel343.setBounds(110, 80, 38, 16);

        jLabel344.setText("jLabel9");
        jPanel51.add(jLabel344);
        jLabel344.setBounds(110, 100, 38, 16);

        jPanel52.setBackground(new java.awt.Color(153, 102, 255));
        jPanel52.setLayout(null);

        jLabel345.setText("Goverment Health Center ");
        jPanel52.add(jLabel345);
        jLabel345.setBounds(50, 10, 140, 16);

        jLabel346.setText("Contact:");
        jPanel52.add(jLabel346);
        jLabel346.setBounds(30, 60, 50, 16);

        jLabel347.setText("Email:");
        jPanel52.add(jLabel347);
        jLabel347.setBounds(30, 80, 32, 16);

        jLabel348.setText("website :");
        jPanel52.add(jLabel348);
        jLabel348.setBounds(30, 100, 60, 16);

        jLabel349.setText("jLabel7");
        jPanel52.add(jLabel349);
        jLabel349.setBounds(110, 50, 37, 16);

        jLabel350.setText("jLabel8");
        jPanel52.add(jLabel350);
        jLabel350.setBounds(110, 80, 38, 16);

        jLabel351.setText("jLabel9");
        jPanel52.add(jLabel351);
        jLabel351.setBounds(110, 100, 38, 16);

        jPanel53.setBackground(new java.awt.Color(153, 102, 255));
        jPanel53.setLayout(null);

        jLabel352.setText("Goverment Health Center ");
        jPanel53.add(jLabel352);
        jLabel352.setBounds(50, 10, 140, 16);

        jLabel353.setText("Contact:");
        jPanel53.add(jLabel353);
        jLabel353.setBounds(30, 60, 50, 16);

        jLabel354.setText("Email:");
        jPanel53.add(jLabel354);
        jLabel354.setBounds(30, 80, 32, 16);

        jLabel355.setText("website :");
        jPanel53.add(jLabel355);
        jLabel355.setBounds(30, 100, 60, 16);

        jLabel356.setText("jLabel7");
        jPanel53.add(jLabel356);
        jLabel356.setBounds(110, 50, 37, 16);

        jLabel357.setText("jLabel8");
        jPanel53.add(jLabel357);
        jLabel357.setBounds(110, 80, 38, 16);

        jLabel358.setText("jLabel9");
        jPanel53.add(jLabel358);
        jLabel358.setBounds(110, 100, 38, 16);

        jPanel54.setBackground(new java.awt.Color(153, 102, 255));
        jPanel54.setLayout(null);

        jLabel359.setText("Goverment Health Center ");
        jPanel54.add(jLabel359);
        jLabel359.setBounds(50, 10, 140, 16);

        jLabel360.setText("Contact:");
        jPanel54.add(jLabel360);
        jLabel360.setBounds(30, 60, 50, 16);

        jLabel361.setText("Email:");
        jPanel54.add(jLabel361);
        jLabel361.setBounds(30, 80, 32, 16);

        jLabel362.setText("website :");
        jPanel54.add(jLabel362);
        jLabel362.setBounds(30, 100, 60, 16);

        jLabel363.setText("jLabel7");
        jPanel54.add(jLabel363);
        jLabel363.setBounds(110, 50, 37, 16);

        jLabel364.setText("jLabel8");
        jPanel54.add(jLabel364);
        jLabel364.setBounds(110, 80, 38, 16);

        jLabel365.setText("jLabel9");
        jPanel54.add(jLabel365);
        jLabel365.setBounds(110, 100, 38, 16);

        jPanel53.add(jPanel54);
        jPanel54.setBounds(110, 300, 240, 150);

        jPanel52.add(jPanel53);
        jPanel53.setBounds(110, 300, 240, 150);

        jPanel51.add(jPanel52);
        jPanel52.setBounds(110, 300, 240, 150);

        jPanel47.add(jPanel51);
        jPanel51.setBounds(230, 350, 240, 150);

        jLabel366.setText("01-5001245");
        jPanel47.add(jLabel366);
        jLabel366.setBounds(110, 50, 120, 16);

        jPanel39.add(jPanel47);
        jPanel47.setBounds(540, 250, 270, 150);

        getContentPane().add(jPanel39);
        jPanel39.setBounds(430, 250, 270, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BG frame.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 1100, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emergencycontact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emergencycontact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emergencycontact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emergencycontact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emergencycontact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel195;
    private javax.swing.JLabel jLabel196;
    private javax.swing.JLabel jLabel197;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel215;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel221;
    private javax.swing.JLabel jLabel222;
    private javax.swing.JLabel jLabel223;
    private javax.swing.JLabel jLabel224;
    private javax.swing.JLabel jLabel225;
    private javax.swing.JLabel jLabel226;
    private javax.swing.JLabel jLabel227;
    private javax.swing.JLabel jLabel228;
    private javax.swing.JLabel jLabel229;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel230;
    private javax.swing.JLabel jLabel231;
    private javax.swing.JLabel jLabel232;
    private javax.swing.JLabel jLabel233;
    private javax.swing.JLabel jLabel234;
    private javax.swing.JLabel jLabel235;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JLabel jLabel241;
    private javax.swing.JLabel jLabel242;
    private javax.swing.JLabel jLabel243;
    private javax.swing.JLabel jLabel244;
    private javax.swing.JLabel jLabel245;
    private javax.swing.JLabel jLabel246;
    private javax.swing.JLabel jLabel247;
    private javax.swing.JLabel jLabel248;
    private javax.swing.JLabel jLabel249;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel250;
    private javax.swing.JLabel jLabel251;
    private javax.swing.JLabel jLabel252;
    private javax.swing.JLabel jLabel253;
    private javax.swing.JLabel jLabel254;
    private javax.swing.JLabel jLabel255;
    private javax.swing.JLabel jLabel256;
    private javax.swing.JLabel jLabel257;
    private javax.swing.JLabel jLabel258;
    private javax.swing.JLabel jLabel259;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel260;
    private javax.swing.JLabel jLabel261;
    private javax.swing.JLabel jLabel262;
    private javax.swing.JLabel jLabel263;
    private javax.swing.JLabel jLabel264;
    private javax.swing.JLabel jLabel265;
    private javax.swing.JLabel jLabel266;
    private javax.swing.JLabel jLabel267;
    private javax.swing.JLabel jLabel268;
    private javax.swing.JLabel jLabel269;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel270;
    private javax.swing.JLabel jLabel271;
    private javax.swing.JLabel jLabel272;
    private javax.swing.JLabel jLabel273;
    private javax.swing.JLabel jLabel274;
    private javax.swing.JLabel jLabel275;
    private javax.swing.JLabel jLabel276;
    private javax.swing.JLabel jLabel277;
    private javax.swing.JLabel jLabel278;
    private javax.swing.JLabel jLabel279;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel280;
    private javax.swing.JLabel jLabel281;
    private javax.swing.JLabel jLabel282;
    private javax.swing.JLabel jLabel283;
    private javax.swing.JLabel jLabel284;
    private javax.swing.JLabel jLabel285;
    private javax.swing.JLabel jLabel286;
    private javax.swing.JLabel jLabel287;
    private javax.swing.JLabel jLabel288;
    private javax.swing.JLabel jLabel289;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel290;
    private javax.swing.JLabel jLabel291;
    private javax.swing.JLabel jLabel292;
    private javax.swing.JLabel jLabel293;
    private javax.swing.JLabel jLabel294;
    private javax.swing.JLabel jLabel295;
    private javax.swing.JLabel jLabel296;
    private javax.swing.JLabel jLabel297;
    private javax.swing.JLabel jLabel298;
    private javax.swing.JLabel jLabel299;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel300;
    private javax.swing.JLabel jLabel301;
    private javax.swing.JLabel jLabel302;
    private javax.swing.JLabel jLabel303;
    private javax.swing.JLabel jLabel304;
    private javax.swing.JLabel jLabel305;
    private javax.swing.JLabel jLabel306;
    private javax.swing.JLabel jLabel307;
    private javax.swing.JLabel jLabel308;
    private javax.swing.JLabel jLabel309;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel310;
    private javax.swing.JLabel jLabel311;
    private javax.swing.JLabel jLabel312;
    private javax.swing.JLabel jLabel313;
    private javax.swing.JLabel jLabel314;
    private javax.swing.JLabel jLabel315;
    private javax.swing.JLabel jLabel316;
    private javax.swing.JLabel jLabel317;
    private javax.swing.JLabel jLabel318;
    private javax.swing.JLabel jLabel319;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel320;
    private javax.swing.JLabel jLabel321;
    private javax.swing.JLabel jLabel322;
    private javax.swing.JLabel jLabel323;
    private javax.swing.JLabel jLabel324;
    private javax.swing.JLabel jLabel325;
    private javax.swing.JLabel jLabel326;
    private javax.swing.JLabel jLabel327;
    private javax.swing.JLabel jLabel328;
    private javax.swing.JLabel jLabel329;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel330;
    private javax.swing.JLabel jLabel331;
    private javax.swing.JLabel jLabel332;
    private javax.swing.JLabel jLabel333;
    private javax.swing.JLabel jLabel334;
    private javax.swing.JLabel jLabel335;
    private javax.swing.JLabel jLabel336;
    private javax.swing.JLabel jLabel337;
    private javax.swing.JLabel jLabel338;
    private javax.swing.JLabel jLabel339;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel340;
    private javax.swing.JLabel jLabel341;
    private javax.swing.JLabel jLabel342;
    private javax.swing.JLabel jLabel343;
    private javax.swing.JLabel jLabel344;
    private javax.swing.JLabel jLabel345;
    private javax.swing.JLabel jLabel346;
    private javax.swing.JLabel jLabel347;
    private javax.swing.JLabel jLabel348;
    private javax.swing.JLabel jLabel349;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel350;
    private javax.swing.JLabel jLabel351;
    private javax.swing.JLabel jLabel352;
    private javax.swing.JLabel jLabel353;
    private javax.swing.JLabel jLabel354;
    private javax.swing.JLabel jLabel355;
    private javax.swing.JLabel jLabel356;
    private javax.swing.JLabel jLabel357;
    private javax.swing.JLabel jLabel358;
    private javax.swing.JLabel jLabel359;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel360;
    private javax.swing.JLabel jLabel361;
    private javax.swing.JLabel jLabel362;
    private javax.swing.JLabel jLabel363;
    private javax.swing.JLabel jLabel364;
    private javax.swing.JLabel jLabel365;
    private javax.swing.JLabel jLabel366;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
