package view;
import javax.swing.JOptionPane;

import controller.UserController;
import models.User;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        cpassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        signUpButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        UPDATES = new javax.swing.JButton();
        ABOUTUS = new javax.swing.JButton();
        APPOIINTMENT = new javax.swing.JButton();
        LOGIN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 650));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));

        jLabel1.setText("SIGN UP");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(600, 130, 110, 30);

        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 200, 34, 16);

        jLabel4.setText("E-MAIL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(550, 250, 210, 16);

        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, 300, 70, 16);

        jLabel6.setText("COMFIRM PASSWORD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(550, 350, 180, 20);

        name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(550, 220, 210, 30);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(550, 270, 210, 30);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(550, 320, 210, 30);
        getContentPane().add(cpassword);
        cpassword.setBounds(550, 372, 210, 30);

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(530, 180, 260, 240);

        signUpButton.setBackground(new java.awt.Color(153, 0, 255));
        signUpButton.setText("SIGN UP");
        signUpButton.setBorder(null);
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signUpButton);
        signUpButton.setBounds(610, 433, 90, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Already  have an account..");
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 480, 200, 23);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setForeground(new java.awt.Color(153, 153, 255));

        UPDATES.setText("UPDATES");
        jPanel3.add(UPDATES);

        ABOUTUS.setText("ABOUT US");
        jPanel3.add(ABOUTUS);

        APPOIINTMENT.setText("APPOIINTMENT");
        jPanel3.add(APPOIINTMENT);

        LOGIN.setText("LOGIN");
        jPanel3.add(LOGIN);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(780, 40, 390, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("Health Track logo smaller.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 10, 230, 290);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("BG frame.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-50, -50, 1170, 810);

        pack();
    }// </editor-fold>                        

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_emailActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
        String Name = name.getText();
        String Email = email.getText();

        String Password = new String(password.getPassword());
        String Cpassword = cpassword.getText();

        int a = 0;
        if (Name.equals("")) {
            JOptionPane.showMessageDialog(null, "NAME IS MISSING.");
            a = 1;
        }
        if (Email.equals("")) {
            JOptionPane.showMessageDialog(null, "Email IS MISSING.");
            a = 1;
        }
        if (Password.equals("")) {
            JOptionPane.showMessageDialog(null, "Password IS MISSING.");
            a = 1;
        }
        if (Cpassword.equals("")) {
            JOptionPane.showMessageDialog(null, "Confirm Password IS MISSING.");
        }
        // if (Password.equals(Cpassword)){
        // JOptionPane.showMessageDialog(null,"VALIDATION SUCCESSFUL");
        // }
        if (!Password.equals(Cpassword)) {
            JOptionPane.showMessageDialog(null, "Password dosenot match");
            a = 1;
        }
        if (a == 0) {

            try {
                User s1 = new User(Name, Email, Password);
                UserController sc = new UserController();
                int insertedStudent = sc.insertDetails(s1);

                if (insertedStudent > 0) {
                    System.out.println("data inserted");
                } else {
                    System.out.println("Failed to insert data");
                }
                JOptionPane.showMessageDialog(null, "VALIDATION SUCCESSFUL");
            } catch (Exception e) {
                // TODO: handle exception
                JOptionPane.showMessageDialog(null, e);
                System.out.printf(null,e);
            }
        }

    }// GEN-LAST:event_signUpButtonActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ABOUTUS;
    private javax.swing.JButton APPOIINTMENT;
    private javax.swing.JButton LOGIN;
    private javax.swing.JButton UPDATES;
    private javax.swing.JPasswordField cpassword;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signUpButton;
    // End of variables declaration                   
}
